name = "SchlichtandersJuliaRegistry"
uuid = "7c7f2fb5-a71b-4c8a-8e5e-a2f18e9b020d"
repo = "git@github.com:schlichtanders/SchlichtandersJuliaRegistry.jl.git"
description = "My public development registry"

[packages]
3311a090-b55d-11e9-176d-dbdfc6a88253 = { name = "ASTParser", path = "A/ASTParser" }
79afa230-ca09-11e8-120b-5decf7bf5e25 = { name = "Continuables", path = "C/Continuables" }
