name = "SchlichtandersJuliaRegistry"
uuid = "7c7f2fb5-a71b-4c8a-8e5e-a2f18e9b020d"
repo = "https://github.com/schlichtanders/SchlichtandersJuliaRegistry.jl"
description = "My public development registry"

[packages]
2704c575-34db-4e2b-9135-fc0075949e5a = { name = "IsDef", path = "I/IsDef" }
3311a090-b55d-11e9-176d-dbdfc6a88253 = { name = "ASTParser", path = "A/ASTParser" }
4a6f0533-cc52-4fcf-a409-c6c05775ac80 = { name = "Monadic", path = "M/Monadic" }
5060dc80-e054-11e8-0acc-1dc6592f659e = { name = "Traits", path = "T/Traits" }
6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c = { name = "StructEquality", path = "S/StructEquality" }
79afa230-ca09-11e8-120b-5decf7bf5e25 = { name = "Continuables", path = "C/Continuables" }
83eed652-29e8-11e9-12da-a7c29d64ffc9 = { name = "DataTypesBasic", path = "D/DataTypesBasic" }
90c4b210-f34a-11e9-1a87-5d0d3aaf0cab = { name = "ProxyInterface", path = "P/ProxyInterface" }
9b3bf0c4-f070-48bc-ae01-f2584e9c23bc = { name = "ProxyInterfaces", path = "P/ProxyInterfaces" }
a3ae8450-d22f-11e9-3fe0-77240e25996f = { name = "SimpleMatch", path = "S/SimpleMatch" }
c5caad1f-83bd-4ce8-ac8e-4b29921e994e = { name = "ExprParsers", path = "E/ExprParsers" }
c9d4e05b-6318-49cb-9b56-e0e2b0ceadd8 = { name = "WhereTraits", path = "W/WhereTraits" }
