name = "SchlichtandersJuliaRegistry"
uuid = "7c7f2fb5-a71b-4c8a-8e5e-a2f18e9b020d"
repo = "git@github.com:schlichtanders/SchlichtandersJuliaRegistry.jl.git"
description = "My public development registry"

[packages]
3311a090-b55d-11e9-176d-dbdfc6a88253 = { name = "ASTParser", path = "A/ASTParser" }
79afa230-ca09-11e8-120b-5decf7bf5e25 = { name = "Continuables", path = "C/Continuables" }
83eed652-29e8-11e9-12da-a7c29d64ffc9 = { name = "DataTypesBasic", path = "D/DataTypesBasic" }
a3ae8450-d22f-11e9-3fe0-77240e25996f = { name = "SimpleMatch", path = "S/SimpleMatch" }
