name = "SchlichtandersJuliaRegistry"
uuid = "7c7f2fb5-a71b-4c8a-8e5e-a2f18e9b020d"
repo = "git@github.com:schlichtanders/SchlichtandersJuliaRegistry.jl.git"
description = "My public development registry"

[packages]
